
document.querySelectorAll('body > app-root > app-pattern-table-list > div > div.flex-container-col.content.ng-star-inserted > app-pattern-table:nth-child(12)')

document.querySelectorAll('body > app-root > app-pattern-table-list > div > div.flex-container-col.content.ng-star-inserted > div.flex-container-col.ng-star-inserted > app-table > div > table')


{
    "neetCodeAll" = [
        "Contains Duplicate",
        "Valid Anagram",
        "Concatenation of Array",
        "Replace Elements With Greatest Element On Right Side",
        "Is Subsequence",
        "Length of Last Word",
        "Two Sum",
        "Longest Common Prefix",
        "Group Anagrams",
        "Pascals Triangle",
        "Remove Element",
        "Unique Email Addresses",
        "Isomorphic Strings",
        "Can Place Flowers",
        "Majority Element",
        "Next Greater Element I",
        "Find Pivot Index",
        "Range Sum Query - Immutable",
        "Find All Numbers Disappeared in An Array",
        "Maximum Number of Balloons",
        "Word Pattern",
        "Design HashSet",
        "Design HashMap",
        "Monotonic Array",
        "Number of Good Pairs",
        "Pascal's Triangle II",
        "Find Words That Can Be Formed by Characters",
        "Largest 3-Same-Digit Number in String",
        "Destination City",
        "Maximum Product Difference Between Two",
        "Maximum Score After Splitting a String",
        "Path Crossing",
        "Minimum Changes To Make Alternating Binary String",
        "Redistribute Characters to Make All Strings Equal",
        "Largest Substring Between Two Equal Characters",
        "Set Mismatch",
        "First Unique Character in a String",
        "Intersection of Two Arrays",
        "Number of Students Unable to Eat Lunch",
        "Time Needed to Buy Tickets",
        "Special Array with X Elements Greater than or Equal X",
        "Sort an Array",
        "Top K Frequent Elements",
        "Encode and Decode Strings",
        "Product of Array Except Self",
        "Valid Sudoku",
        "Longest Consecutive Sequence",
        "Sort Colors",
        "Encode and Decode TinyURL",
        "Brick Wall",
        "Best Time to Buy And Sell Stock II",
        "Subarray Sum Equals K",
        "Unique Length 3 Palindromic Subsequences",
        "Minimum Number of Swaps to Make The String Balanced",
        "Number of Pairs of Interchangeable Rectangles",
        "Maximum Product of The Length of Two Palindromic Subsequences",
        "Grid Game",
        "Find All Anagrams in a String",
        "Find The Index of The First Occurrence in a String",
        "Wiggle Sort",
        "Largest Number",
        "Continuous Subarray Sum",
        "Push Dominoes",
        "Repeated DNA Sequences",
        "Insert Delete Get Random O(1)",
        "Check if a String Contains all Binary Codes of Size K",
        "Range Sum Query 2D Immutable",
        "Non Decreasing Array",
        "First Missing Positive",
        "Sign of An Array",
        "Find the Difference of Two Arrays",
        "Design Parking System",
        "Number of Zero-Filled Subarrays",
        "Optimal Partition of String",
        "Design Underground System",
        "Minimum Penalty for a Shop",
        "Champagne Tower",
        "Majority Element II",
        "Sum of Absolute Differences in a Sorted Array",
        "Design a Food Rating System",
        "Convert an Array Into a 2D Array With Conditions",
        "Minimum Numbers of Operations to Make Array Empty",
        "Divide Array Into Arrays With Max Difference",
        "Sequential Digits",
        "Sort Characters By Frequency",
        "Find Polygon with the Largest Perimeter",
        "Minimum Remove to Make Valid Parentheses",
        "Contiguous Array",
        "Find All Duplicates in an Array",
        "Text Justification",
        "Naming a Company",
        "Number of Submatrices that Sum to Target",
        "Valid Palindrome",
        "Valid Palindrome II",
        "Minimum Difference Between Highest And Lowest of K Scores",
        "Merge Strings Alternately",
        "Reverse String",
        "Merge Sorted Array",
        "Move Zeroes",
        "Remove Duplicates From Sorted Array",
        "Assign Cookies",
        "Find First Palindromic String in the Array",
        "Sort Array by Parity",
        "Reverse Words in a String III",
        "Backspace String Compare",
        "Check If Two String Arrays are Equivalent",
        "Remove Duplicates From Sorted Array II",
        "Two Sum II Input Array Is Sorted",
        "3Sum",
        "4Sum",
        "Container With Most Water",
        "Number of Subsequences That Satisfy The Given Sum Condition",
        "Rotate Array",
        "Array With Elements Not Equal to Average of Neighbors",
        "Boats to Save People",
        "K-th Symbol in Grammar",
        "Minimum Time To Make Rope Colorful",
        "Rearrange Array Elements by Sign",
        "Bag of Tokens",
        "Minimum Length of String after Deleting Similar Ends",
        "Trapping Rain Water",
        "Best Time to Buy And Sell Stock",
        "Contains Duplicate II",
        "Number of Sub Arrays of Size K and Avg Greater than or Equal to Threshold",
        "Longest Substring Without Repeating Characters",
        "Longest Repeating Character Replacement",
        "Permutation In String",
        "Frequency of The Most Frequent Element",
        "Fruits into Basket",
        "Maximum Number of Vowels in a Substring of Given Length",
        "Minimum Number of Flips to Make The Binary String Alternating",
        "Minimum Size Subarray Sum",
        "Find K Closest Elements",
        "Minimum Operations to Reduce X to Zero",
        "Get Equal Substrings Within Budget",
        "Binary Subarrays with Sum",
        "Subarray Product Less Than K",
        "Length of Longest Subarray With at Most K Frequency",
        "Count Subarrays Where Max Element Appears at Least K Times",
        "Minimum Window Substring",
        "Sliding Window Maximum",
        "Subarrays with K Different Integers",
        "Minimum Number of Operations to Make Array Continuous",
        "Valid Parentheses",
        "Baseball Game",
        "Implement Stack Using Queues",
        "Implement Queue using Stacks",
        "Make The String Great",
        "Min Stack",
        "Evaluate Reverse Polish Notation",
        "Removing Stars From a String",
        "Validate Stack Sequences",
        "Generate Parentheses",
        "Asteroid Collision",
        "Daily Temperatures",
        "Online Stock Span",
        "Car Fleet",
        "Simplify Path",
        "Decode String",
        "Remove K Digits",
        "Remove All Adjacent Duplicates In String II",
        "132 Pattern",
        "Flatten Nested List Iterator",
        "Sum of Subarray Minimums",
        "Maximum Frequency Stack",
        "Largest Rectangle In Histogram",
        "Binary Search",
        "Search Insert Position",
        "Guess Number Higher Or Lower",
        "Arranging Coins",
        "Squares of a Sorted Array",
        "Valid Perfect Square",
        "Sqrt(x)",
        "Single Element in a Sorted Array",
        "Capacity to Ship Packages",
        "Find Peak Element",
        "Successful Pairs of Spells and Potions",
        "Search a 2D Matrix",
        "Koko Eating Bananas",
        "Minimize the Maximum Difference of Pairs",
        "Find Minimum In Rotated Sorted Array",
        "Search In Rotated Sorted Array",
        "Search In Rotated Sorted Array II",
        "Time Based Key Value Store",
        "Find First And Last Position of Element In Sorted Array",
        "Maximum Number of Removable Characters",
        "Populating Next Right Pointers In Each Node",
        "Search Suggestions System",
        "Split Array Largest Sum",
        "Median of Two Sorted Arrays",
        "Find in Mountain Array",
        "Reverse Linked List",
        "Merge Two Sorted Lists",
        "Palindrome Linked List",
        "Remove Linked List Elements",
        "Remove Duplicates From Sorted List",
        "Middle of the Linked List",
        "Intersection of Two Linked Lists",
        "Merge in Between Linked Lists",
        "Remove Nodes From Linked List",
        "Reorder List",
        "Maximum Twin Sum Of A Linked List",
        "Remove Nth Node From End of List",
        "Swapping Nodes in a Linked List",
        "LFU Cache",
        "Copy List With Random Pointer",
        "Design Linked List", "Design Browser History", "Add Two Numbers", "Linked List Cycle",
        "Find The Duplicate Number", "Swap Nodes In Pairs", "Sort List", "Partition List", "Rotate List",
        "Reverse Linked List II", "Design Circular Queue", "Insertion Sort List", "Split Linked List in Parts",
        "LRU Cache", "Merge K Sorted Lists", "Reverse Nodes In K Group", "Binary Tree Inorder Traversal",
        "Binary Tree Preorder Traversal", "Binary Tree Postorder Traversal", "Invert Binary Tree",
        "Maximum Depth of Binary Tree", "Diameter of Binary Tree", "Balanced Binary Tree", "Same Tree",
        "Subtree of Another Tree", "Convert Sorted Array to Binary Search Tree", "Merge Two Binary Trees",
        "Path Sum", "Range Sum of BST", "Leaf-Similar Trees", "Evaluate Boolean Binary Tree",
        "Construct String From Binary Tree", "Lowest Common Ancestor of a Binary Search Tree",
        "Insert into a Binary Search Tree", "Delete Node in a BST", "Binary Tree Level Order Traversal",
        "Binary Tree Right Side View", "Minimum Distance between BST Nodes", "Symmetric Tree",
        "Minimum Time to Collect All Apples in a Tree", "Binary Tree Zigzag Level Order Traversal",
        "Construct Quad Tree", "Find Duplicate Subtrees", "Check Completeness of a Binary Tree",
        "Construct Binary Tree from Inorder and Postorder Traversal", "Maximum Width of Binary Tree",
        "Time Needed to Inform All Employees", "Count Good Nodes In Binary Tree", "Validate Binary Search Tree",
        "Kth Smallest Element In a Bst", "Construct Binary Tree From Preorder And Inorder Traversal",
        "Unique Binary Search Trees", "Unique Binary Search Trees II", "Sum Root to Leaf Numbers",
        "House Robber III", "Flip Equivalent Binary Trees", "Operations On Tree",
        "All Possible Full Binary Trees", "Find Bottom Left Tree Value", "Trim a Binary Search Tree",
        "Binary Search Tree Iterator", "Validate Binary Tree Nodes", "Find Largest Value in Tree Row",
        "Pseudo-Palindromic Paths in a Binary Tree", "Even Odd Tree", "Smallest String Starting From Leaf",
        "Delete Leaves With a Given Value", "Distribute Coins in Binary Tree", "Convert Bst to Greater Tree",
        "Binary Tree Maximum Path Sum", "Serialize And Deserialize Binary Tree", "Kth Largest Element In a Stream",
        "Last Stone Weight", "K Closest Points to Origin", "Kth Largest Element In An Array", "Task Scheduler",
        "Design Twitter", "Least Number of Unique Integers after K Removal", "Furthest Building You Can Reach",
        "Minimize Deviation in Array", "Maximum Subsequence Score", "Single Threaded Cpu", "Seat Reservation Manager",
        "Process Tasks Using Servers", "Find The Kth Largest Integer In The Array", "Reorganize String",
        "Longest Happy String", "Car Pooling", "Find Median From Data Stream", "Maximum Performance of a Team",
        "IPO", "Minimum Cost to Hire K Workers", "Number of Flowers in Full Bloom", "Constrained Subsequence Sum",
        "Sum of All Subsets XOR Total", "Subsets", "Combination Sum", "Combinations", "Permutations", "Subsets II",
        "Combination Sum II", "Permutations II", "Word Search", "Palindrome Partitioning", "Restore IP Addresses",
        "Letter Combinations of a Phone Number", "Matchsticks to Square", "Splitting a String Into Descending Consecutive Values",
        "Find Unique Binary String", "Maximum Length of a Concatenated String With Unique Characters",
        "Partition to K Equal Sum Subsets", "The Number of Beautiful Subsets", "N Queens", "N Queens II",
        "Maximum Score Words Formed By Letters", "Word Break II", "Implement Trie Prefix Tree",
        "Design Add And Search Words Data Structure", "Extra Characters in a String", "Word Search II",
        "Island Perimeter", "Verifying An Alien Dictionary", "Find the Town Judge", "Number of Islands",
        "Max Area of Island", "Clone Graph", "Walls And Gates", "Rotting Oranges", "Count Sub Islands",
        "Pacific Atlantic Water Flow", "Surrounded Regions", "Reorder Routes to Make All Paths Lead to The City Zero",
        "Snakes And Ladders", "Open The Lock", "Find Eventual Safe States", "Course Schedule", "Course Schedule II",
        "Graph Valid Tree", "Course Schedule IV", "Check if Move Is Legal", "Shortest Bridge", "Shortest Path in Binary Matrix",
        "Number of Connected Components In An Undirected Graph", "Redundant Connection", "Accounts Merge",
        "Find Closest Node to Given Two Nodes", "As Far from Land as Possible", "Shortest Path with Alternating Colors",
        "Minimum Fuel Cost to Report to the Capital", "Minimum Score of a Path Between Two Cities", "Number of Closed Islands",
        "Number of Enclaves", "Minimum Number of Vertices to Reach all Nodes", "Is Graph Bipartite?", "Evaluate Division",
        "Detonate the Maximum Bombs", "Minimum Height Trees", "Path with Maximum Gold", "Largest Color Value in a Directed Graph",
        "Minimum Number of Days to Eat N Oranges", "Parallel Courses III", "Find All People With Secret", "Word Ladder",
        "Path with Minimum Effort", "Reconstruct Itinerary", "Min Cost to Connect All Points", "Network Delay Time",
        "Path with Maximum Probability", "Find the Safest Path in a Grid", "Swim In Rising Water", "Alien Dictionary",
        "Cheapest Flights Within K Stops", "Number of Good Paths", "Remove Max Number of Edges to Keep Graph Fully Traversable",
        "Find Critical and Pseudo Critical Edges in Minimum Spanning Tree", "Greatest Common Divisor Traversal",
        "Climbing Stairs", "Min Cost Climbing Stairs", "House Robber", "House Robber II", "Longest Palindromic Substring",
        "Palindromic Substrings", "Decode Ways", "Coin Change", "Maximum Product Subarray", "Word Break", "Longest Increasing Subsequence",
        "Partition Equal Subset Sum", "Triangle", "Delete And Earn", "Paint House", "Combination Sum IV", "Perfect Squares",
        "Check if There is a Valid Partition For The Array", "Maximum Subarray Min Product", "Minimum Cost For Tickets",
        "Integer Break", "Number of Longest Increasing Subsequence", "Stickers to Spell Word", "N-th Tribonacci Number",
        "Uncrossed Lines", "Solving Questions With Brainpower", "Count Ways to Build Good Strings", "New 21 Game",
        "Best Team with no Conflicts", "Longest String Chain", "Knight Dialer", "Partition Array for Maximum Sum",
        "Largest Divisible Subset", "Stone Game III", "Concatenated Words", "Maximize Score after N Operations",
        "Find the Longest Valid Obstacle Course at Each Position", "Count all Valid Pickup and Delivery Options",
        "Number of Ways to Divide a Long Corridor", "Maximum Profit in Job Scheduling", "Student Attendance Record II",
        "Unique Paths", "Unique Paths II", "Longest Common Subsequence", "Longest Palindromic Subsequence",
        "Last Stone Weight II", "Best Time to Buy And Sell Stock With Cooldown", "Coin Change II", "Target Sum",
        "Interleaving String", "Stone Game", "Minimum Path Sum", "Longest Increasing Path In a Matrix", "Maximal Square",
        "Ones and Zeroes", "Maximum Alternating Subsequence Sum", "Distinct Subsequences", "Edit Distance",
        "Number of Dice Rolls with Target Sum", "Minimum Falling Path Sum", "Out of Boundary Paths", "Longest Ideal Subsequence",
        "Count Vowels Permutation", "Burst Balloons", "Number of Ways to Rearrange Sticks With K Elements",
        "Image Smoother", "Count of Matches in Tournament", "Largest Local Values in a Matrix",
        "Power of Four", "Maximum Points on a Line", "Rotate Image", "Spiral Matrix", "Spiral Matrix II",
        "Set Matrix Zeroes", "Happy Number", "Plus One", "Palindrome Number", "Ugly Number", "Shift 2D Grid",
        "Roman to Integer", "Integer to Roman", "Pow(x, n)", "Multiply Strings", "Detect Squares",
        "Robot Bounded In Circle", "Zigzag Conversion", "Find Missing Observations", "Largest Submatrix With Rearrangements",
        "Wildest Vertical Area Between Two Points Containing No Points", "Minimum Number of One Bit Operations to Make Integers Zero",
        "Single Number", "Single Number III", "Number of 1 Bits", "Counting Bits", "Reverse Bits", "Missing Number",
        "Shuffle the Array", "Add to Array-Form of Integer", "Find the Difference", "Power of Two", "Sum of Two Integers",
        "Reverse Integer", "Bitwise AND of Numbers Range", "Count Triplets That Can Form Two Arrays of Equal XOR",
        "Add Binary", "Create Hello World Function", "Counter", "Counter II", "Apply Transform over each Element in Array",
        "Filter Elements from Array", "Array Reduce Transformation", "Function Composition", "Allow One Function Call",
        "Memoize", "Curry", "Sleep", "Promise Time Limit", "Promise Pool", "Cache With Time Limit", "Debounce",
        "Throttle", "JSON Deep Equal", "Convert Object to JSON String", "Array of Objects to Matrix",
        "Difference Between Two Objects", "Chunk Array", "Flatten Deeply Nested Array", "Array Prototype Last",
        "Group By", "Check if Object Instance of Class", "Call Function with Custom Context", "Event Emitter",
        "Array Wrapper", "Generate Fibonacci Sequence", "Nested Array Generator"


    ]
}

console.log(neetCodeAll.length);











